/**
 * The portable test suite. Runs against `fixtures/synthetic-sch.json`, generated by
 * `make-synthetic.mjs` and containing no real design data — so these tests work for
 * anyone who clones the repo, with EasyEDA closed.
 *
 * The synthetic board is built specifically to contain the cases that broke, or
 * nearly broke, the model during development against a real board.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

import { listComponents, parseCPara } from '../src/server/model/components.js';
import { buildNetlist, findNet, pinNetIndex } from '../src/server/model/nets.js';
import { docKind } from '../src/server/model/document.js';
import { listComponentsText } from '../src/server/tools/list-components.js';
import { listNetsText, traceNetText } from '../src/server/tools/nets.js';
import { getComponentText } from '../src/server/tools/component.js';
import { buildBom, getBomText } from '../src/server/tools/bom.js';
import type { StdDocument } from '../src/server/model/types.js';

const here = dirname(fileURLToPath(import.meta.url));
const doc = JSON.parse(
  readFileSync(resolve(here, '../../test/fixtures/synthetic-sch.json'), 'utf8'),
) as StdDocument;

test('synthetic: recognised as a schematic', () => {
  assert.equal(docKind(doc), 'schematic');
});

test('synthetic: sheet frame excluded, all real components found', () => {
  const comps = listComponents(doc);
  assert.equal(Object.keys(doc.schlib ?? {}).length, 19, '19 schlib entries = 18 parts + frame');
  assert.equal(comps.length, 18);
  assert.ok(!comps.some((c) => c.designator === 'frame_lib_1'));
});

test('synthetic: designators sort naturally, not lexically', () => {
  const caps = listComponents(doc)
    .map((c) => c.designator)
    .filter((d) => /^C\d+$/.test(d));
  assert.deepEqual(caps, ['C1', 'C2', 'C3', 'C4', 'C5', 'C6']);
});

test('synthetic: c_para yields identity fields', () => {
  const u1 = listComponents(doc).find((c) => c.designator === 'U1')!;
  assert.equal(u1.name, 'LDO33-A');
  assert.equal(u1.footprint, 'SOT-23-5');
  assert.equal(u1.supplierPart, 'C7001002');
  assert.equal(u1.manufacturer, 'GenericSemi');
  assert.equal(u1.manufacturerPart, 'GS-LDO33A');
});

test('synthetic: a part with no LCSC number does not get one invented', () => {
  const h1 = listComponents(doc).find((c) => c.designator === 'H1')!;
  assert.equal(h1.supplierPart, undefined);
  assert.equal(h1.inBom, false, 'add_into_bom=no must be honoured');
});

test('synthetic: parseCPara round-trips the generated encoding', () => {
  const p = parseCPara('package`R0402`Supplier`LCSC`Supplier Part`C7003001`');
  assert.deepEqual(p, { package: 'R0402', Supplier: 'LCSC', 'Supplier Part': 'C7003001' });
});

test('synthetic: netlist is healthy', () => {
  const nl = buildNetlist(doc);
  assert.equal(nl.diagnostics.totalPins, 46);
  assert.equal(nl.diagnostics.orphanPins, 0, 'every pin must land on the graph');
  assert.deepEqual(nl.diagnostics.nameConflicts, [], 'a conflict means two rails got merged');
});

test('synthetic: disjoint same-named netflags merge into one net', () => {
  // Twelve separate GND symbols with no wire between them. Without the merge pass
  // this becomes twelve one-pin "nets" — which looks plausible and is wrong.
  const gnd = findNet(buildNetlist(doc), 'GND')!;
  assert.equal(gnd.pins.length, 12);
  assert.deepEqual(
    gnd.pins.map((p) => `${p.designator}.${p.pinNumber}`).sort(),
    ['C1.2', 'C2.2', 'C3.2', 'C4.2', 'C5.2', 'C6.2', 'D1.2', 'J1.2', 'R4.2', 'U1.2', 'U2.2', 'U3.2'],
  );
});

test('synthetic: power rails stay distinct from each other', () => {
  const nl = buildNetlist(doc);
  assert.equal(findNet(nl, '+3V3')!.pins.length, 9);
  assert.equal(findNet(nl, 'VBUS')!.pins.length, 5);
  // The regression this guards: a stray wire once shorted +3V3 to GND, which the
  // nameConflicts diagnostic caught.
  const rail = new Set(findNet(nl, '+3V3')!.pins.map((p) => `${p.designator}.${p.pinNumber}`));
  for (const p of findNet(nl, 'GND')!.pins) {
    assert.ok(!rail.has(`${p.designator}.${p.pinNumber}`), 'a pin cannot be on both GND and +3V3');
  }
});

test('synthetic: I2C nets span the whole sheet through polyline corners', () => {
  const nl = buildNetlist(doc);
  assert.deepEqual(
    findNet(nl, 'SDA')!.pins.map((p) => `${p.designator}.${p.pinNumber}`).sort(),
    ['J1.3', 'R1.1', 'U2.3', 'U3.3'],
  );
  assert.deepEqual(
    findNet(nl, 'SCL')!.pins.map((p) => `${p.designator}.${p.pinNumber}`).sort(),
    ['J1.4', 'R2.1', 'R4.1', 'U2.4', 'U3.4'],
  );
});

test('synthetic: unnamed local nets are kept with unique stable ids', () => {
  const nl = buildNetlist(doc);
  const unnamed = nl.nets.filter((n) => !n.name && n.pins.length > 1);
  assert.equal(unnamed.length, 4, 'crystal x2, LED drive, LED anode');
  assert.ok(unnamed.every((n) => /^N\$\d+$/.test(n.id)));
  assert.equal(new Set(nl.nets.map((n) => n.id)).size, nl.nets.length, 'ids must be unique');
});

test('synthetic: unconnected pins are reported as such, not as nets', () => {
  const text = getComponentText(doc, 'U2');
  const row = text.split('\n').find((l) => /^8\s/.test(l.trim()));
  assert.ok(row?.includes('(unconnected)'), `U2.8 (RESET) should be unconnected, got: ${row}`);
  assert.ok(!/N\$/.test(row!), 'must not invent a net id for an unconnected pin');

  // 12 groups total, 3 of them single-pin => 9 real nets shown by default.
  assert.ok(/9 nets/.test(listNetsText(doc)));
  assert.ok(/3 unconnected pin\(s\) excluded/.test(listNetsText(doc)));
});

test('synthetic: includeUnconnected restores the full set', () => {
  const all = listNetsText(doc, { includeUnconnected: true, limit: 100 });
  assert.ok(/12 nets/.test(all));
});

test('synthetic: pin -> net index agrees with the netlist', () => {
  const index = pinNetIndex(buildNetlist(doc));
  assert.equal(index.get('U2.1')?.name, '+3V3');
  assert.equal(index.get('U2.2')?.name, 'GND');
  assert.equal(index.get('U2.3')?.name, 'SDA');
  assert.equal(index.get('U2.5')?.name, undefined, 'crystal net is unnamed');
});

test('synthetic: a component with zero pins is still listed', () => {
  const tp = listComponents(doc).find((c) => c.designator === 'TP1')!;
  assert.equal(tp.pinCount, 0);
  assert.ok(listComponentsText(doc).includes('TP1'));
});

test('synthetic: BOM keeps the same value in different packages apart', () => {
  const { lines, excluded } = buildBom(doc);
  const tenK = lines.filter((l) => l.name === '10kΩ');
  assert.equal(tenK.length, 2, '10k in R0402 and R0603 are two line items');
  assert.deepEqual(tenK.map((l) => l.footprint).sort(), ['R0402', 'R0603']);
  assert.deepEqual(excluded.map((c) => c.designator), ['H1']);
});

test('synthetic: BOM quantities reconcile exactly', () => {
  const { lines, excluded } = buildBom(doc);
  const total = lines.reduce((a, l) => a + l.quantity, 0);
  assert.equal(total + excluded.length, listComponents(doc).length);
  for (const l of lines) assert.equal(l.designators.length, l.quantity);

  const seen = new Set<string>();
  for (const l of lines) {
    for (const d of l.designators) {
      assert.ok(!seen.has(d), `${d} appears on more than one BOM line`);
      seen.add(d);
    }
  }
  assert.ok(/12 BOM lines covering 17 components/.test(getBomText(doc)));
});

test('synthetic: trace_net names the owning component', () => {
  const text = traceNetText(doc, 'SDA');
  assert.ok(text.includes('4 connection(s)'));
  assert.ok(text.includes('MCU32-A'), 'should resolve U2 to its part name');
  assert.ok(text.includes('TEMP-SENS-A'));
});

test('synthetic: tool output stays bounded and leaks no geometry', () => {
  for (const text of [listComponentsText(doc), listNetsText(doc), getBomText(doc), getComponentText(doc, 'U2')]) {
    assert.ok(text.length < 20_000);
    assert.ok(!text.includes('pointArr'));
    assert.ok(!text.includes('c_para'));
  }
});
